apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-2
spec: 
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/
    repoURL: https://github.com/loydpadgett/argoCD.git
    targetRevision: main
