apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-prod
spec: 
  destination:
    namespace: argocd-install
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: argo-cd/
    repoURL: https://github.com/loydpadgett/argoCD.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
