apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.8/manifests/ha/install.yaml
  - resources/namespace.yaml
patchesStrategicMerge:
  - patches/argocd-cm.yaml